CREATE TABLE performancereviews (
    REVIEW_ID NUMBER(38) NOT NULL PRIMARY KEY,
    EMPLOYEE_ID NUMBER(38),
    REVIEW_DATE DATE,
    PERFORMANCE_SCORE NUMBER(3,2),
    GOALS_ACHIEVED VARCHAR2(255),
    AREAS_IMPROVEMENT VARCHAR2(255),
    REVIEWER_ID NUMBER(38),
    NEXT_REVIEW_DATE DATE
);

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (1, 101, TO_DATE('2023-03-15', 'YYYY-MM-DD'), 8, 'Exceeded sales target by 20%', 'Time management', 201, TO_DATE('2024-03-15', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (2, 102, TO_DATE('2023-04-10', 'YYYY-MM-DD'), 3, 'Met most project deadlines', 'Communication skills', 202, TO_DATE('2024-04-10', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (3, 103, TO_DATE('2023-05-20', 'YYYY-MM-DD'), 9, 'Successfully led team project', 'Delegation skills', 203, TO_DATE('2024-05-20', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (4, 104, TO_DATE('2023-06-18', 'YYYY-MM-DD'), 3, 'Achieved 90% of performance goals', 'Focus on detail', 204, TO_DATE('2024-06-18', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (5, 105, TO_DATE('2023-07-25', 'YYYY-MM-DD'), 5, 'Completed training certifications', 'Punctuality', 205, TO_DATE('2024-07-25', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (6, 106, TO_DATE('2023-08-30', 'YYYY-MM-DD'), 6, 'Exceeded KPIs for the quarter', 'Conflict resolution', 206, TO_DATE('2024-08-30', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (7, 107, TO_DATE('2023-09-10', 'YYYY-MM-DD'), 8, 'Consistently met project deadlines', 'Leadership development', 207, TO_DATE('2024-09-10', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (8, 108, TO_DATE('2023-10-05', 'YYYY-MM-DD'), 9, 'Improved customer satisfaction scores', 'Team collaboration', 208, TO_DATE('2024-10-05', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (9, 109, TO_DATE('2023-11-12', 'YYYY-MM-DD'), 9, 'Successfully handled critical client issues', 'Presentation skills', 209, TO_DATE('2024-11-12', 'YYYY-MM-DD'));

INSERT INTO performancereviews (REVIEW_ID, EMPLOYEE_ID, REVIEW_DATE, PERFORMANCE_SCORE, GOALS_ACHIEVED, AREAS_IMPROVEMENT, REVIEWER_ID, NEXT_REVIEW_DATE)
VALUES (10, 110, TO_DATE('2023-12-15', 'YYYY-MM-DD'), 8, 'Exceeded all personal and team goals', 'Time management', 210, TO_DATE('2024-12-15', 'YYYY-MM-DD'));
